#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

set -e # die on error

# yarn prettier // commented because it causes alot of unncecessary changes that are not related to the commit
yarn turbo run extract-translations
yarn pretty-quick --staged
