name: OHRI Config - Importmap, Deployment

on:
  push:
    branches:
      - dev_config-cd
      - working_config-cd
      - demo_config-cd

  pull_request:
    branches:
      - dev_config
      - working_config
      - demo_config
    types: [opened, synchronize]

  release:
    types:
      - created
jobs:
  rename_import_map_working:
    runs-on: ubuntu-latest

    if: ${{ github.ref == 'refs/heads/working_config' }}

    steps:
      - name: SSH into Dev Server and rename, backup importmap
        uses: garygrossgarten/github-action-ssh@release
        # uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HISTAC_HOST }}
          username: ${{ secrets.HISTAC_USERNAME }}
          privateKey: ${{ secrets.HISTAC_KEY}}
          port: ${{ secrets.HISTAC_PORT }}
          command: |
            cd /usr/share/tomcat/microfrontends/working
            mv importmap.json importmap_backup_$(date +"%Y-%m-%d").json

  update_import_map_working:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Branch Dev Import Map to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: config/importmap_dev.json
          remote: /usr/share/tomcat/microfrontends/working
          host: ${{ secrets.HISTAC_HOST }}
          username: ${{ secrets.HISTAC_USERNAME }}
          privateKey: ${{ secrets.HISTAC_KEY}}
          port: ${{ secrets.HISTAC_PORT }}
